### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by otaolafranc** [LIHPC-Computational-Geometry/HexMeshWorkshop#1]
Hello,
I would love to test the different algorithms inside this git but when I enter the documentation the installation section is empty. would it be possible to give some instructions on how to achieve it installation in linux?
thanks in advance

**Comment by sebmestrallet** [comment]
Hello ! Thanks for your interest.

This project is only a tool for my PhD and is not meant for broader use yet.

Nevertheless I added some notes in the [Installation](https://github.com/LIHPC-Computational-Geometry/HexMeshWorkshop/wiki/User-documentation#installation) section, let me know if it works for you.

The issue is that a lot of the executables (labeling generation, file conversion) are developed in a private repo, so most Python scripts will fail. This other repo will be accessible after publication of the main algorithm.

**Comment by otaolafranc** [comment]
Hello sebastien,
sorry I got in your personal repo! I was simply looking at the LIHPC github and I found this. this installs the dependencies? from what I imagine the answer is a no? as algoHex has gurobi dependency which is close source for example... I see that you work with christophe bourcier nice! I cross him in the salome workshop day. are any plans of the LIHPC different projects to be integrated to salome itself?
best regards and good luck with the thesis!

**Comment by sebmestrallet** [comment]
Thank you!

I made this personal repo public because there is nothing sensitive, it's just a convenient way to manage data folders.

Most of the LIHPC projects are managed uniformly with Spack, but PhD students don't have those constraints for their repos. Mine doesn't install anything, all dependencies have to be installed manually and their path must be provided in `settings.json`.

SALOME is not developed by the LIHPC. You should ask your question to the SALOME support.

**Comment by otaolafranc** [comment]
>SALOME is not developed by the LIHPC. You should ask your question to the SALOME support.
oh I know it is simply that I saw the salome logo at the end of your installation guide [link](https://github.com/LIHPC-Computational-Geometry/HexMeshWorkshop/wiki/User-documentation#global_padding) thats why I was curious about
best regards

**Comment by sebmestrallet** [comment]
Yes, Christophe is one of my supervisors, but I'm not part of the development discussions for SALOME 😉
